'use client'

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/HJuaG0lAsWs
 */

import { CardTitle, CardContent, Card } from '@/components/ui/card'

import { ResponsiveBar } from '@nivo/bar'
import { ResponsiveLine } from '@nivo/line'
import {
    TableHead,
    TableRow,
    TableHeader,
    TableCell,
    TableBody,
    Table,
} from '@/components/ui/table'
import { FunctionComponent } from 'react'
import { User } from '@prisma/client'
import dayjs from 'dayjs'

type DashboardProps = {
    users: User[]
}

export const Dashboard: FunctionComponent<DashboardProps> = ({ users }) => {
    const started = users?.filter((user) => user.startedAt !== null).length
    const finished = users?.filter((user) => user.finishedAt !== null).length

    return (
        <>
            <div className="grid gap-4 md:grid-cols-2">
                <Card>
                    <CardContent className="item flex h-full flex-col items-center justify-center">
                        <CardTitle className="my-2 text-sm font-semibold tracking-wide">
                            Started onboarding
                        </CardTitle>
                        <p className="text-9xl"> {started} </p>
                    </CardContent>
                </Card>
                <Card>
                    <CardContent className="item flex h-full flex-col items-center justify-center">
                        <CardTitle className="my-2 text-sm font-semibold tracking-wide">
                            Finished onboarding
                        </CardTitle>
                        <p className="text-9xl"> {finished} </p>
                    </CardContent>
                </Card>
                {/* <Card>
                    <CardContent className="flex flex-col gap-1">
                        <CardTitle className="my-2 text-sm font-semibold tracking-wide">
                            Completed onboarding
                        </CardTitle>
                        <BarChart className="h-[150px]" />
                        <CardTitle className="text-2xl font-bold">
                            {stats?.started}
                        </CardTitle>
                    </CardContent>
                </Card> */}
                {/* <Card>
                    <CardContent className="mt-2 flex flex-col gap-1">
                        <CardTitle className="text-sm font-semibold tracking-wide">
                            Active Projects
                        </CardTitle>
                        <FilledtimeseriesChart className="h-[150px]" />
                        <CardTitle className="text-2xl font-bold">56</CardTitle>
                    </CardContent>
                </Card> */}
                <Card>
                    <CardContent className="flex flex-col gap-1">
                        <CardTitle className="my-2 text-sm font-semibold tracking-wide">
                            Average Onboarding Time
                        </CardTitle>
                        <LineChart className="h-[150px]" />
                        <CardTitle className="text-2xl font-bold">
                            3.5 days
                        </CardTitle>
                    </CardContent>
                </Card>
            </div>
            <Card>
                <Table>
                    <TableHeader>
                        <TableRow>
                            <TableHead>Name</TableHead>
                            <TableHead className="hidden md:table-cell">
                                Email
                            </TableHead>
                            <TableHead className="hidden md:table-cell">
                                Start date
                            </TableHead>
                            <TableHead className="hidden md:table-cell">
                                completed
                            </TableHead>
                        </TableRow>
                    </TableHeader>
                    <TableBody>
                        {users?.map((user) => {
                            return (
                                <TableRow key={user.id}>
                                    <TableCell className="font-medium">
                                        {user.id}
                                    </TableCell>
                                    <TableCell className="hidden md:table-cell">
                                        not implemented
                                    </TableCell>
                                    <TableCell className="hidden md:table-cell">
                                        {user?.startedAt
                                            ? dayjs(user.startedAt).format(
                                                  'DD/MM/YYYY'
                                              )
                                            : 'not started'}
                                    </TableCell>
                                    <TableCell className="hidden md:table-cell">
                                        {user?.finishedAt
                                            ? dayjs(user.finishedAt).format(
                                                  'DD/MM/YYYY'
                                              )
                                            : 'not completed'}
                                    </TableCell>
                                </TableRow>
                            )
                        })}
                    </TableBody>
                </Table>
            </Card>
        </>
    )
}

function BarChart(props: { className: string }) {
    return (
        <div {...props}>
            <ResponsiveBar
                data={[
                    { name: 'Jan', count: 111 },
                    { name: 'Feb', count: 157 },
                    { name: 'Mar', count: 129 },
                    { name: 'Apr', count: 150 },
                    { name: 'May', count: 119 },
                    { name: 'Jun', count: 72 },
                ]}
                keys={['count']}
                indexBy="name"
                margin={{ top: 0, right: 0, bottom: 40, left: 40 }}
                padding={0.3}
                colors={['#2563eb']}
                axisBottom={{
                    tickSize: 0,
                    tickPadding: 16,
                }}
                axisLeft={{
                    tickSize: 0,
                    tickValues: 4,
                    tickPadding: 16,
                }}
                gridYValues={4}
                theme={{
                    tooltip: {
                        chip: {
                            borderRadius: '9999px',
                        },
                        container: {
                            fontSize: '12px',
                            textTransform: 'capitalize',
                            borderRadius: '6px',
                        },
                    },
                    grid: {
                        line: {
                            stroke: '#f3f4f6',
                        },
                    },
                }}
                tooltipLabel={({ id }) => `${id}`}
                enableLabel={false}
                role="application"
                ariaLabel="A bar chart showing data"
            />
        </div>
    )
}

function FilledtimeseriesChart(props: { className: string }) {
    return (
        <div {...props}>
            <ResponsiveLine
                data={[
                    {
                        id: 'Desktop',
                        data: [
                            { x: 'Jan', y: 43 },
                            { x: 'Feb', y: 137 },
                            { x: 'Mar', y: 61 },
                            { x: 'Apr', y: 145 },
                            { x: 'May', y: 26 },
                            { x: 'Jun', y: 154 },
                        ],
                    },
                    {
                        id: 'Mobile',
                        data: [
                            { x: 'Jan', y: 60 },
                            { x: 'Feb', y: 48 },
                            { x: 'Mar', y: 177 },
                            { x: 'Apr', y: 78 },
                            { x: 'May', y: 96 },
                            { x: 'Jun', y: 204 },
                        ],
                    },
                ]}
                margin={{ top: 10, right: 10, bottom: 40, left: 40 }}
                xScale={{
                    type: 'point',
                }}
                yScale={{
                    type: 'linear',
                    min: 0,
                    max: 'auto',
                }}
                axisTop={null}
                axisRight={null}
                axisBottom={{
                    tickSize: 0,
                    tickPadding: 16,
                }}
                axisLeft={{
                    tickSize: 0,
                    tickValues: 5,
                    tickPadding: 16,
                }}
                colors={['#2563eb', '#e11d48']}
                pointSize={6}
                useMesh={true}
                curve="monotoneX"
                enableArea={true}
                gridYValues={6}
                defs={[
                    {
                        id: 'line-chart-gradient',
                        type: 'linearGradient',
                        colors: [
                            { offset: 0, color: 'inherit' },
                            { offset: 200, color: 'inherit', opacity: 0 },
                        ],
                    },
                ]}
                fill={[{ match: '*', id: 'line-chart-gradient' }]}
                theme={{
                    tooltip: {
                        chip: {
                            borderRadius: '9999px',
                        },
                        container: {
                            fontSize: '12px',
                            textTransform: 'capitalize',
                            borderRadius: '6px',
                        },
                    },
                    grid: {
                        line: {
                            stroke: '#f3f4f6',
                        },
                    },
                }}
                role="application"
            />
        </div>
    )
}

function LineChart(props: { className: string }) {
    return (
        <div {...props}>
            <ResponsiveLine
                data={[
                    {
                        id: 'Desktop',
                        data: [
                            { x: 'Jan', y: 0 },
                            { x: 'Feb', y: 137 },
                            { x: 'Mar', y: 61 },
                            { x: 'Apr', y: 145 },
                            { x: 'May', y: 26 },
                            { x: 'Jun', y: 154 },
                        ],
                    },
                    {
                        id: 'Mobile',
                        data: [
                            { x: 'Jan', y: 60 },
                            { x: 'Feb', y: 48 },
                            { x: 'Mar', y: 177 },
                            { x: 'Apr', y: 78 },
                            { x: 'May', y: 96 },
                            { x: 'Jun', y: 204 },
                        ],
                    },
                ]}
                margin={{ top: 10, right: 10, bottom: 40, left: 40 }}
                xScale={{
                    type: 'point',
                }}
                yScale={{
                    type: 'linear',
                }}
                axisTop={null}
                axisRight={null}
                axisBottom={{
                    tickSize: 0,
                    tickPadding: 16,
                }}
                axisLeft={{
                    tickSize: 0,
                    tickValues: 5,
                    tickPadding: 16,
                }}
                colors={['#2563eb', '#e11d48']}
                pointSize={6}
                useMesh={true}
                gridYValues={6}
                theme={{
                    tooltip: {
                        chip: {
                            borderRadius: '9999px',
                        },
                        container: {
                            fontSize: '12px',
                            textTransform: 'capitalize',
                            borderRadius: '6px',
                        },
                    },
                    grid: {
                        line: {
                            stroke: '#f3f4f6',
                        },
                    },
                }}
                role="application"
            />
        </div>
    )
}
